sudo: false

services:
  - docker

before_install:
  - docker build -t gustavo/datajud-integration -f Dockerfile .

script:
  - docker run -e CI=true gustavo/datajud-integration npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "tryout"
  env: "Tryout-env"
  bucket_name: "elasticbeanstalk-us-east-1-830665105132"
  bucket_path: "tryout"
  on:
    branch: master
  access_key_id: "$SECRET_ID"
  secret_access_key: "$SECRET_KEY"
