version: '3.8'
services:
  backend_db:
    container_name: backend_db
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - "5432:5432"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - backend_db
    container_name: nest
    environment:
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_NAME: ${DATABASE_NAME}
      DATAJUD_API_KEY: ${DATAJUD_API_KEY}
      DATAJUD_API_URL: ${DATAJUD_API_URL}
    ports:
      - '3000:3000'
    volumes:
      - ./src:/app/src


